version: "3.7"
   
services:
  
  paxos-1:
    image: paxos
    command: ./ptp-paxos-bin alice 8080
    ports:
      - "8080:8080"
  
  paxos-2:
    image: paxos
    command: ./ptp-paxos-bin bob 8081
    ports:
      - "8081:8081"
  
  paxos-3:
    image: paxos
    command: ./ptp-paxos-bin charlie 8082
    ports:
      - "8082:8082"

  submitter-1:
    image: submitter
    command: ./ptp-submitter-bin paxos-1:8080 paxos-2:8081 paxos-3:8082
    ports:
      - "8181:8181"
