########################################

FROM haskell:8.8.4 AS paxos-lib-build
RUN cabal v2-update
WORKDIR /usr/src/haskell
COPY ptp.cabal .
RUN cabal v2-build ptp-paxos-lib --dependencies-only
COPY ptp-paxos-src ./ptp-paxos-src
RUN cabal v2-build ptp-paxos-lib

########################################

FROM paxos-lib-build AS submitter-lib-build
COPY ptp-submitter-src ./ptp-submitter-src
RUN cabal v2-build ptp-submitter-lib

########################################

FROM submitter-lib-build AS submitter-bin-build
RUN cabal v2-build ptp-submitter-bin

########################################

FROM debian:buster

RUN apt-get install -y libgmp10  && \
    apt-get clean                && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /paxos

COPY --from=submitter-bin-build /usr/src/haskell/dist-newstyle/build/x86_64-linux/ghc-8.8.4/ptp-paxos-0.1.0.0/x/ptp-submitter-bin/build/ptp-submitter-bin/ptp-submitter-bin .
